# Generated by Django 6.0.3 on 2026-03-24 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pieces/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('shirt', 'Parte de cima (Blusas, Camisas, Casacos)'), ('pants', 'Parte de baixo (Calças, Saias, Shorts)'), ('shoes', 'Sapatos e Calçados')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
