# Generated by Django 6.0.3 on 2026-03-26 14:02

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='pants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_pants', to='wardrobe.piece'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_shirt', to='wardrobe.piece'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_shoes', to='wardrobe.piece'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='outfits/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='pieces/'),
        ),
    ]
